services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app/backend
    environment:
      - NODE_ENV=development
    networks:
      - auditor-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - auditor-network

  auditor:
    build: .
    command: python /app/test_run.py
    ports:
      - "8501:8501"
    volumes:
      - .:/app
      - ../data-masc:/app/data/dataset
    environment:
      PYTHONUNBUFFERED: "1"
    networks:
      - auditor-network

networks:
  auditor-network:
    driver: bridge
