"""Crop-level accessibility-violation classifier (MobileNetV3 / EfficientNet-B0).

Generated by notebooks/train_crop_violation_classifier.ipynb. Given a
cropped region of a screenshot, predicts which of R09 (low contrast), R04
(small touch target), R17 (insufficient spacing), R10 (text overflow),
R28 (font-scale overflow) and R08 (layout overlap) it violates - the rules
identified in docs/user_coverage_for_training.md as needing pixel-level
confirmation beyond what the XML rule checker (src/rules.py) can see.
"""
from __future__ import annotations

from pathlib import Path

import torch
from PIL import Image
from torchvision import transforms
from torchvision.models import efficientnet_b0, mobilenet_v3_large, mobilenet_v3_small

DEFAULT_WEIGHTS = Path(__file__).resolve().parents[1] / "models" / "crop_violation_classifier_best.pt"

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

_model_cache: dict[str, tuple] = {}


def _build_backbone(name: str, num_classes: int):
    if name == "mobilenet_v3_small":
        model = mobilenet_v3_small(weights=None)
        model.classifier[-1] = torch.nn.Linear(model.classifier[-1].in_features, num_classes)
    elif name == "mobilenet_v3_large":
        model = mobilenet_v3_large(weights=None)
        model.classifier[-1] = torch.nn.Linear(model.classifier[-1].in_features, num_classes)
    elif name == "efficientnet_b0":
        model = efficientnet_b0(weights=None)
        model.classifier[-1] = torch.nn.Linear(model.classifier[-1].in_features, num_classes)
    else:
        raise ValueError(f"Unknown backbone: {name!r}")
    return model


def _get_model(weights_path: str | Path):
    key = str(weights_path)
    if key not in _model_cache:
        ckpt = torch.load(key, map_location="cpu")
        rule_classes = ckpt["rule_classes"]
        model = _build_backbone(ckpt["backbone"], num_classes=len(rule_classes))
        model.load_state_dict(ckpt["model_state"])
        model.eval()
        transform = transforms.Compose([
            transforms.Resize((ckpt["crop_size"], ckpt["crop_size"])),
            transforms.ToTensor(),
            transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
        ])
        _model_cache[key] = (model, transform, rule_classes)
    return _model_cache[key]


def classify_crop(
    image_path: str | Path,
    bounds: list[int] | None = None,
    weights_path: str | Path = DEFAULT_WEIGHTS,
    threshold: float = 0.5,
) -> dict[str, float]:
    """Classify one crop (or one region of a larger screenshot).

    If bounds=[left, top, right, bottom] is given, that region is cropped
    out of the image first; otherwise the whole image is treated as the
    crop. Returns {rule_id: probability} for every rule the model predicts
    above `threshold`, plus every rule's raw probability under "_all".
    """
    model, transform, rule_classes = _get_model(weights_path)
    img = Image.open(image_path).convert("RGB")
    if bounds is not None:
        img = img.crop(tuple(bounds))

    with torch.no_grad():
        tensor = transform(img).unsqueeze(0)
        probs = torch.sigmoid(model(tensor))[0].tolist()

    result = {"_all": dict(zip(rule_classes, probs))}
    for rule, prob in zip(rule_classes, probs):
        if prob >= threshold:
            result[rule] = prob
    return result


# Rules with real positive training signal (confirmed non-zero support in
# both the MASC test split and the Rico holdout eval - see
# docs/progress/Supplementary_Progress_Report_v1.24.md §15G.3/§15G.5).
# R09/R10/R28 are in the checkpoint's label set but have ~0 positive
# training examples, so a probability from them would be untrained noise,
# not signal - deliberately excluded from confirmation.
CV_CONFIRMABLE_RULES = {"R08", "R17", "R04"}


def confirm_violations(violations_doc: dict, screenshot_path: str | Path) -> dict:
    """Attach a pixel-level cv_confidence to violations whose rule has real
    CV training signal. Mutates and returns violations_doc in place.

    Additive only, per FR-CV.2: never removes a violation or changes its
    severity based on the CV result. A CV failure (corrupt image, model
    load issue) never raises - it just leaves cv_confidence as None, since
    this is a supplementary signal and must not break the underlying,
    already-valid XML-based audit.
    """
    for violation in violations_doc.get("violations", []):
        if violation["rule_id"] not in CV_CONFIRMABLE_RULES:
            continue
        try:
            result = classify_crop(screenshot_path, bounds=violation["bounds"])
            violation["cv_confidence"] = round(result["_all"][violation["rule_id"]], 4)
        except Exception:
            violation["cv_confidence"] = None
    return violations_doc
