"""TQ>>>Crop-level accessibility-violation classifier.

Generated by notebooks/train_crop_violation_classifier.ipynb. Given a
cropped region of a screenshot, predicts which of R09 (low contrast), R04
(small touch target), R17 (insufficient spacing), R10 (text overflow),
R28 (font-scale overflow) and R08 (layout overlap) it violates - the rules
identified in docs/user_coverage_for_training.md as needing pixel-level
confirmation beyond what the XML rule checker (src/rules.py) can see.

Every one of the 33 backbones from docs/picking_model_for_crop.md's
comparison sweep gets its own explicit branch below (no dict lookup, no
generic timm fallback) so it's unambiguous which backbone maps to which
constructor call.
"""
from __future__ import annotations

from pathlib import Path

import torch
import torch.nn as nn
from PIL import Image
from torchvision import transforms
from torchvision.models import (
    DenseNet121_Weights,
    ConvNeXt_Tiny_Weights,
    EfficientNet_B0_Weights,
    EfficientNet_V2_S_Weights,
    MNASNet1_0_Weights,
    MobileNet_V3_Large_Weights,
    MobileNet_V3_Small_Weights,
    RegNet_Y_800MF_Weights,
    ResNet50_Weights,
    ShuffleNet_V2_X1_0_Weights,
    SqueezeNet1_1_Weights,
    ViT_B_16_Weights,
    densenet121,
    convnext_tiny,
    efficientnet_b0,
    efficientnet_v2_s,
    mnasnet1_0,
    mobilenet_v3_large,
    mobilenet_v3_small,
    regnet_y_800mf,
    resnet50,
    shufflenet_v2_x1_0,
    squeezenet1_1,
    vit_b_16,
)

try:
    import timm
except ImportError:
    timm = None


DEFAULT_WEIGHTS = Path(__file__).resolve().parents[1] / "models" / "crop_violation_classifier_best.pt"

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]

_model_cache: dict[str, tuple] = {}


def _build_backbone(name: str, num_classes: int):
    if name == "mobilenet_v3_small":
        model = mobilenet_v3_small(weights=None)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)
    elif name == "mobilenet_v3_large":
        model = mobilenet_v3_large(weights=None)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)
    elif name == "efficientnet_b0":
        model = efficientnet_b0(weights=None)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)
    elif name == "efficientnet_v2_s":
        model = efficientnet_v2_s(weights=None)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)
    elif name == "mnasnet1_0":
        model = mnasnet1_0(weights=None)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)
    elif name == "resnet50":
        model = resnet50(weights=None)
        model.fc = nn.Linear(model.fc.in_features, num_classes)
    elif name == "shufflenet_v2_x1_0":
        model = shufflenet_v2_x1_0(weights=None)
        model.fc = nn.Linear(model.fc.in_features, num_classes)
    elif name == "regnet_y_800mf":
        model = regnet_y_800mf(weights=None)
        model.fc = nn.Linear(model.fc.in_features, num_classes)
    elif name == "densenet121":
        model = densenet121(weights=None)
        model.classifier = nn.Linear(model.classifier.in_features, num_classes)
    elif name == "squeezenet1_1":
        model = squeezenet1_1(weights=None)
        model.classifier[1] = nn.Conv2d(model.classifier[1].in_channels, num_classes, kernel_size=1)
    elif name == "vit_b_16":
        model = vit_b_16(weights=None)
        model.heads.head = nn.Linear(model.heads.head.in_features, num_classes)
    elif name == "mobilevit_s":
        if timm is None:
            raise ImportError("mobilevit_s requires `timm` (pip install timm)")
        model = timm.create_model("mobilevit_s", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv1_100":
        if timm is None:
            raise ImportError("mobilenetv1_100 requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv1_100", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv1_125":
        if timm is None:
            raise ImportError("mobilenetv1_125 requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv1_125", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv2_050":
        if timm is None:
            raise ImportError("mobilenetv2_050 requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv2_050", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv2_100":
        if timm is None:
            raise ImportError("mobilenetv2_100 requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv2_100", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv2_140":
        if timm is None:
            raise ImportError("mobilenetv2_140 requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv2_140", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv3_small_050":
        if timm is None:
            raise ImportError("mobilenetv3_small_050 requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv3_small_050", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv3_small_100":
        if timm is None:
            raise ImportError("mobilenetv3_small_100 requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv3_small_100", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv3_large_100":
        if timm is None:
            raise ImportError("mobilenetv3_large_100 requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv3_large_100", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv4_conv_small":
        if timm is None:
            raise ImportError("mobilenetv4_conv_small requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv4_conv_small", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv4_conv_medium":
        if timm is None:
            raise ImportError("mobilenetv4_conv_medium requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv4_conv_medium", pretrained=False, num_classes=num_classes)
    elif name == "mobilenetv4_conv_large":
        if timm is None:
            raise ImportError("mobilenetv4_conv_large requires `timm` (pip install timm)")
        model = timm.create_model("mobilenetv4_conv_large", pretrained=False, num_classes=num_classes)
    elif name == "mobilevit_xxs":
        if timm is None:
            raise ImportError("mobilevit_xxs requires `timm` (pip install timm)")
        model = timm.create_model("mobilevit_xxs", pretrained=False, num_classes=num_classes)
    elif name == "mobilevit_xs":
        if timm is None:
            raise ImportError("mobilevit_xs requires `timm` (pip install timm)")
        model = timm.create_model("mobilevit_xs", pretrained=False, num_classes=num_classes)
    elif name == "mobilevitv2_050":
        if timm is None:
            raise ImportError("mobilevitv2_050 requires `timm` (pip install timm)")
        model = timm.create_model("mobilevitv2_050", pretrained=False, num_classes=num_classes)
    elif name == "mobilevitv2_100":
        if timm is None:
            raise ImportError("mobilevitv2_100 requires `timm` (pip install timm)")
        model = timm.create_model("mobilevitv2_100", pretrained=False, num_classes=num_classes)
    elif name == "mobilevitv2_200":
        if timm is None:
            raise ImportError("mobilevitv2_200 requires `timm` (pip install timm)")
        model = timm.create_model("mobilevitv2_200", pretrained=False, num_classes=num_classes)
    elif name == "mobileone_s0":
        if timm is None:
            raise ImportError("mobileone_s0 requires `timm` (pip install timm)")
        model = timm.create_model("mobileone_s0", pretrained=False, num_classes=num_classes)
    elif name == "mobileone_s1":
        if timm is None:
            raise ImportError("mobileone_s1 requires `timm` (pip install timm)")
        model = timm.create_model("mobileone_s1", pretrained=False, num_classes=num_classes)
    elif name == "mobileone_s4":
        if timm is None:
            raise ImportError("mobileone_s4 requires `timm` (pip install timm)")
        model = timm.create_model("mobileone_s4", pretrained=False, num_classes=num_classes)
    elif name == "ghostnet_100":
        if timm is None:
            raise ImportError("ghostnet_100 requires `timm` (pip install timm)")
        model = timm.create_model("ghostnet_100", pretrained=False, num_classes=num_classes)
    elif name == "ghostnetv2_100":
        if timm is None:
            raise ImportError("ghostnetv2_100 requires `timm` (pip install timm)")
        model = timm.create_model("ghostnetv2_100", pretrained=False, num_classes=num_classes)
    elif name == "convnext_tiny":
        model = convnext_tiny(weights=None)
        model.classifier[-1] = nn.Linear(model.classifier[-1].in_features, num_classes)
    elif name == "swin_tiny_patch4_window7_224":
        if timm is None:
            raise ImportError("swin_tiny_patch4_window7_224 requires `timm` (pip install timm)")
        model = timm.create_model("swin_tiny_patch4_window7_224", pretrained=False, num_classes=num_classes)
    else:
        raise ValueError(f"Unknown backbone: {name!r}")
    return model


def _get_model(weights_path: str | Path):
    key = str(weights_path)
    if key not in _model_cache:
        ckpt = torch.load(key, map_location="cpu")
        rule_classes = ckpt["rule_classes"]
        model = _build_backbone(ckpt["backbone"], num_classes=len(rule_classes))
        model.load_state_dict(ckpt["model_state"])
        model.eval()
        transform = transforms.Compose([
            transforms.Resize((ckpt["crop_size"], ckpt["crop_size"])),
            transforms.ToTensor(),
            transforms.Normalize(IMAGENET_MEAN, IMAGENET_STD),
        ])
        _model_cache[key] = (model, transform, rule_classes)
    return _model_cache[key]


def classify_crop(
    image_path: str | Path,
    bounds: list[int] | None = None,
    weights_path: str | Path = DEFAULT_WEIGHTS,
    threshold: float = 0.5,
) -> dict[str, float]:
    """Classify one crop (or one region of a larger screenshot).

    If bounds=[left, top, right, bottom] is given, that region is cropped
    out of the image first; otherwise the whole image is treated as the
    crop. Returns {rule_id: probability} for every rule the model predicts
    above `threshold`, plus every rule's raw probability under "_all".
    """
    model, transform, rule_classes = _get_model(weights_path)
    img = Image.open(image_path).convert("RGB")
    if bounds is not None:
        img = img.crop(tuple(bounds))

    with torch.no_grad():
        tensor = transform(img).unsqueeze(0)
        probs = torch.sigmoid(model(tensor))[0].tolist()

    result = {"_all": dict(zip(rule_classes, probs))}
    for rule, prob in zip(rule_classes, probs):
        if prob >= threshold:
            result[rule] = prob
    return result


CV_CONFIRMABLE_RULES = {"R08", "R17", "R04"}


def confirm_violations(violations_doc: dict, screenshot_path: str | Path) -> dict:
    """Attach a pixel-level cv_confidence to violations whose rule has real
    CV training signal. Mutates and returns violations_doc in place.

    Additive only, per FR-CV.2: never removes a violation or changes its
    severity based on the CV result. A CV failure (corrupt image, model
    load issue) never raises - it just leaves cv_confidence as None, since
    this is a supplementary signal and must not break the underlying,
    already-valid XML-based audit.
    """
    for violation in violations_doc.get("violations", []):
        if violation["rule_id"] not in CV_CONFIRMABLE_RULES:
            continue
        try:
            result = classify_crop(screenshot_path, bounds=violation["bounds"])
            violation["cv_confidence"] = round(result["_all"][violation["rule_id"]], 4)
        except Exception:
            violation["cv_confidence"] = None
    return violations_doc
