"""Screenshot-only Android UI element detector (YOLO, fine-tuned).

Generated by notebooks/train_yolo_ui_detector.ipynb. Used when no XML view
hierarchy is available for a screen, so the accessibility auditor can still
locate and classify UI elements from pixels alone.
"""
from __future__ import annotations

from pathlib import Path

from ultralytics import YOLO

DEFAULT_WEIGHTS = Path(__file__).resolve().parents[1] / "models" / "yolo_ui_detector_best.pt"

_model_cache: dict[str, YOLO] = {}


def _get_model(weights_path: str | Path) -> YOLO:
    """Load and cache a YOLO model for a checkpoint path — one load per process, not per call."""
    key = str(weights_path)
    if key not in _model_cache:
        _model_cache[key] = YOLO(key)
    return _model_cache[key]


def detect_ui(image_path: str | Path, weights_path: str | Path = DEFAULT_WEIGHTS, conf: float = 0.25) -> list[dict]:
    """Run the fine-tuned detector on one screenshot.

    Returns a list of {"bbox": [x1, y1, x2, y2], "class": str, "conf": float}
    dicts, one per detected UI element, in the original image's pixel space.
    """
    model = _get_model(weights_path)
    result = model.predict(source=str(image_path), conf=conf, verbose=False)[0]
    names = result.names
    detections = []
    for box in result.boxes:
        x1, y1, x2, y2 = (float(v) for v in box.xyxy[0])
        detections.append({
            "bbox": [x1, y1, x2, y2],
            "class": names[int(box.cls[0])],
            "conf": float(box.conf[0]),
        })
    return detections


# Classes whose real-world Android widgets are normally interactive - used to
# infer clickable/focusable, since YOLO only gives us a class name and box,
# never the underlying view attributes an XML hierarchy would carry.
CLICKABLE_CLASSES = {
    "button_labeled", "button_icon_only", "input_field",
    "checkbox_toggle", "tab_item", "list_item",
}


def detections_to_components(detections: list[dict]) -> list[dict]:
    """Map detect_ui() output into components.json-shaped entries.

    Every field the rule checker (src/rules.py) or its schema requires gets a
    safe default (empty string / False), since pixel detections carry no text,
    content_desc, or view-attribute data an XML hierarchy would have. Each
    component is tagged inferred: true (FR-CV.7) so downstream consumers can
    tell pixel-inferred components apart from real XML-parsed ones.
    """
    components = []
    for i, det in enumerate(detections, start=1):
        cls = det["class"]
        clickable = cls in CLICKABLE_CLASSES
        components.append({
            "component_id": f"c_{i:03d}",
            "class": cls,
            "text": "",
            "content_desc": "",
            "hint": "",
            "resource_id": "",
            "clickable": clickable,
            "enabled": True,
            "focusable": clickable,
            "bounds": [int(v) for v in det["bbox"]],
            "focus_order": i,
            "parent_id": "",
            "long_clickable": False,
            "scrollable": False,
            "selected": False,
            "checked": False,
            "password": False,
            "text_all_caps": False,
            "input_type": "",
            "important_for_accessibility": "",
            "media_type": "",
            "is_dialog": False,
            "label_for": "",
            "visible": True,
            "inferred": True,
        })
    return components
