"""Screenshot-only Android UI element detector (YOLO, fine-tuned).

Generated by notebooks/train_yolo_ui_detector.ipynb. Used when no XML view
hierarchy is available for a screen, so the accessibility auditor can still
locate and classify UI elements from pixels alone.
"""
from __future__ import annotations

from pathlib import Path

from ultralytics import YOLO

DEFAULT_WEIGHTS = Path(__file__).resolve().parents[1] / "models" / "yolo_ui_detector_best.pt"

_model_cache: dict[str, YOLO] = {}


def _get_model(weights_path: str | Path) -> YOLO:
    key = str(weights_path)
    if key not in _model_cache:
        _model_cache[key] = YOLO(key)
    return _model_cache[key]


def detect_ui(image_path: str | Path, weights_path: str | Path = DEFAULT_WEIGHTS, conf: float = 0.25) -> list[dict]:
    """Run the fine-tuned detector on one screenshot.

    Returns a list of {"bbox": [x1, y1, x2, y2], "class": str, "conf": float}
    dicts, one per detected UI element, in the original image's pixel space.
    """
    model = _get_model(weights_path)
    result = model.predict(source=str(image_path), conf=conf, verbose=False)[0]
    names = result.names
    detections = []
    for box in result.boxes:
        x1, y1, x2, y2 = (float(v) for v in box.xyxy[0])
        detections.append({
            "bbox": [x1, y1, x2, y2],
            "class": names[int(box.cls[0])],
            "conf": float(box.conf[0]),
        })
    return detections
